#!/bin/bash
#  Copyright 2023 The original authors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -e

BASEDIR=$(dirname "$(readlink -f $0)")
DOCKERDIR="$BASEDIR"

echo -e "\n🐳 Stopping previous Kafka Docker-Compose stacks..."
for COMPOSE in "$DOCKERDIR/"*.yml; do
  echo "Removing stack for $COMPOSE"
  (cd "$BASEDIR"; docker compose -f "$COMPOSE" down --remove-orphans --volumes)
done

exit 0;
